### ISSUE TITLE
Can't handle empty directories

### ISSUE THREAD

**Issue by enkessler** [jarmo/require_all#10]
The current version of the gem will raise an error if it encounters an empty directory. A quick glance at the code makes me think that it considers an empty directory to be an indication that something has gone wrong while reading the file system. As opposed to it treating empty directories as legitimate things that might exist on the file system.

**Comment by jarmo** [comment]
Thanks for reporting that. I'd be happy to accept a pull request, but probably not going to have time to fix it myself.

**Comment by enkessler** [comment]
Okay. I can probably get around to it sometime in the coming week.

**Comment by enkessler** [comment]
I was using this issue as a 'Hello World' example for someone interested in open source development, so it took a little longer to get around to doing it myself.

Now that I have addressed the issue, it seems like a suspiciously easy fix. Partially because it was a one line change and partially because no existing tests were broken by changing that one line.
