### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by jnardone** [jarmo/require_all#14]
The Gemspec says the license is MIT, but the LICENSE file is some weird version of the Ruby license (but with GPL shown instead of BSDL) (see: https://www.ruby-lang.org/en/about/license.txt)

Please clarify.

**Comment by jarmo** [comment]
Thank you for noticing!

I guess I've added MIT to gemspec without having too much thought about it at the time. It's been a honest mistake so I've removed license type from gemspec. License will stay as it is originally because changing it properly would involve too much work.

**Comment by jnardone** [comment]
You may want to reconsider. Almost no gems I've seen use a GPL-based license; I can tell you this will all but assure that we will trigger fun conversations with our lawyers about its use in our software. But thanks for clarifying.

**Comment by jarmo** [comment]
@jnardone I would like to need to contact every contributor so far and ask their permission to change the license, and I just do not have time to do it right now.

If you or anyone else is willing to take this as their personal task then I'd happily change license to MIT.

**Comment by jarmo** [comment]
License is now fixed to MIT in version 1.4.0. Closing this.
