### ISSUE TITLE
Your NameError logic needs to be more selective

### ISSUE THREAD

**Issue by lardcanoe** [jarmo/require_all#19]
Some of my code was throwing:

```
NoMethodError: undefined method `foo'
```

and since: `class NoMethodError < NameError` it was getting caught by the NameError logic. The file was then getting required again by the loop, but since I was using `::ActiveSupport::Concern` a module was getting included multiple times which led to its own error, which was really confusing.

So just fix up the rescue to not catch descendants of `NameError`

Thanks!

**Comment by jarmo** [comment]
Please send me a PR so that I can release new version with this fix applied. Closing this until then.
