### ISSUE TITLE
Unable to install in application's Gemfile or outside of it

### ISSUE THREAD

**Issue by AutumnJ** [jarmo/require_all#23]
Gemfile contains: 
`gem 'require_all'`

And environment contains: 
`require 'require_all' `

But that produces the following error: 
`require': cannot load such file -- require_all (LoadError)

Outside of my application, I used `gem install require_all` to install locally, and received a successful install message:
Successfully installed require_all-1.5.0
Parsing documentation for require_all-1.5.0
Done installing documentation for require_all after 0 seconds
1 gem installed

But the gem is not listed when I list all gems or use `bundle info require_all` to find details on require_all. Are there any dependencies I should be aware of, which might prevent me from installing within an application or outside of one?

**Comment by enkessler** [comment]
And the Ruby installation to which you installed the gem is the same Ruby installation that you are using to run your program? For example, did you install ththe gem on the command line but run the program from an IDE, which might have been configured to use a different Ruby installation?

**Comment by AutumnJ** [comment]
Great question - I'm on Ruby version 2.4.2 and running the program from my command line via shotgun (not an IDE - just using sublime, terminal & shotgun). And I did not require a different version of Ruby in my application, so there shouldn't be any Ruby version/environment conflicts.

**Comment by enkessler** [comment]
1. 'gem install require_all' (does it install successfully?)
2. 'gem list' (is it now in the list?)
3. 'bundle exec irb' (from whatever folder your gemfile is in)
4 'require 'require_all' (should work fine)

Can you do all of these steps and, if not, where does it go wrong?

**Comment by AutumnJ** [comment]
1. `gem install require_all` does install successfully:
Successfully installed require_all-1.5.0
Parsing documentation for require_all-1.5.0
Done installing documentation for require_all after 0 seconds
1 gem installed

2. `require_all` is _not_ listed when I run `gem list`

3. Ran `bundle exec irb` from application folder containing gemfile.

4. `require 'require_all'` results in error message:
`LoadError: cannot load such file -- require_all`

*I'm also requiring the capybara gem in my Gemfile, and when I use `require 'capybara/dsl'` in irb for step 4, I receive a result of true - no issues there.

**Comment by AutumnJ** [comment]
Closing this issue - thanks for helping troubleshoot! It seems to have been caused by an issue with bundler, which wasn't resolving dependencies correctly. And outside of that, an issue with the rack and sinatra versions running on my computer and in my application. Those are resolved and `require_all` is visible on my local gem list and usable in my application as well.
