### ISSUE TITLE
require_all does not respect $LOAD_PATH

### ISSUE THREAD

**Issue by olerass** [jarmo/require_all#6]
RSpec automatically adds the `lib` directory to $LOAD_PATH, but it seems like require_all doesn't respect it since it cannot load relative files that work fine with normal ruby `require`.

For example, with this class located in `lib/a/test_class.rb`:
```ruby
module A
  class TestClass
    def self.hello
      'Hello, world!'
    end
  end
end
```
and this spec in `spec/test_class_spec.rb`:
```ruby
require 'require_all'
# This works: require 'a/test_class'
require_all 'a' # This doesn't work

describe 'TestClass' do
  it 'says hello' do
    expect(A::TestClass.hello).to eq 'Hello, world!'
  end
end
```
I get the following error: `'rescue in require_all': no such file to load -- a (LoadError)`.

Example project code: http://www.filedropper.com/requireall-example

**Comment by jarmo** [comment]
Closing this due to given workaround.
